name: gex_webapp_kit_client
version: 0.1.0+24
description: Provide a set of common WebComponent and classes to be able to build responsive web applications.
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  logging: '>=0.9.2 <0.10.0'
  paper_elements: '>=0.6.0 <0.7.0'
  polymer: '>=0.15.0 <0.16.0'
  shelf: '>=0.5.6 <0.6.0'
  shelf_static: '>=0.2.1 <0.3.0'
  google_oauth2_client: '>=0.3.4  <0.4.0'  
dev_dependencies:
  mockito: '>=0.8.1 <0.9.0'
  unittest: '>=0.11.4 <0.12.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
    - test/test_button.html
    - test/test_toolbar.html
    - test/test_view_port.html
    - test/test_application.html
    - test/test_bus.html
    - test/test_routing.html
- $dart2js:
    commandLineOptions:
    - --enable-enum
